### ISSUE TITLE
Only show title and check button of finished steps

### ISSUE THREAD

**Issue by Kubik-Rubik** [plesk/ext-welcome-guide#4]
Remove the image, description and action buttons from already checked steps to keep the output cleaner and put the focus of the users on the remaining tasks.

![screenshot 2018-07-10 09 59 46](https://user-images.githubusercontent.com/1976103/42497137-8de9af9c-8428-11e8-8478-95d8639d8f5c.png)

**Comment by Crixu** [comment]
My proposal:

If the status changes to completed

- Change the image span class from `pul-icon--size-64` to `pul-icon--size-32`
- Set the style of the span `pul-item__body` to `display: none`
- Set the style of the button `pul-button--primary` to `display: none`
- reduce the size of the div `welcome-single-item`

**Comment by Kubik-Rubik** [comment]
@Crixu Yes, the CSS adjustment would also be my approach. Seems to be the easiest solution here!

**Comment by Crixu** [comment]
Created Pull request to solve this issue:

https://github.com/plesk/ext-welcome-guide/pull/9
